### PR TITLE
Create ETL for  KVP LHIV TRACKER OFFSITE REGISTER

### PR DESCRIPTION
**Pull request by gabriel090**

### CODE REVIEW

**Review by patryllus — CHANGES_REQUESTED** [review]
Screenshot from 2024-06-26 10-32-16

**Comment by patryllus** [comment]
Remove unreleated changes

**Comment by gabriel090** [comment]
> Screenshot from 2024-06-26 10-32-16


fixed. Thanks

**Review by patryllus — APPROVED** [review]
Merging for tests

**Pull request merged**
